on:
  issues:
    types: [opened,reopened]

name: Create Database

env:
  DATABASE_PROJECT: './demos/database/CatsOfTheWorld/CatsOfTheWorld.sqlproj'

jobs:
  add_database:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'database')
    permissions:
      issues: write      # Add this to ensure proper permissions
      contents: read     # Add this if you need repo access

    steps:
    - name: Issue Forms Body Parser
      id: parse
      uses: zentered/issue-forms-body-parser@v2.0.0
  
    - name: lets see what we got
      shell: pwsh
      run: |
        $results = '${{ toJSON(steps.parse.outputs.data) }}'
        $results = $results | ConvertFrom-Json 

        $results

        $finalRes = $results | ConvertFrom-Json # not sure why we need 2?

        $finalRes

        $Environment = $finalRes.'environment'.text
        $Database = $finalRes.'database'.text
        $RecoveryModel = $finalRes.'recovery-model'.text

        Write-Host ('Environment: {0}' -f $Environment)
        Write-Host ('Database: {0}' -f $Database)
        Write-Host ('Recovery Model: {0}' -f $RecoveryModel)

        echo "SQL_SERVER=$Environment" >> $env:GITHUB_ENV
        echo "SQL_DATABASE=$Database" >> $env:GITHUB_ENV
        echo "RECOVERY_MODEL=$RecoveryModel" >> $env:GITHUB_ENV
    
    - name: Install and cache PowerShell modules
      uses: potatoqualitee/psmodulecache@v6.2.1
      with:
        modules-to-cache: dbatools

    - name: Do we have dbatools?
      shell: pwsh
      run: |
        Get-Module dbatools -ListAvailable

    - name: Get SQL Server info from Terraform
      shell: pwsh
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      run: |
        cd demos/databaseDevops/terraform
        terraform init -backend-config="key=cotw-${{ env.Environment }}.terraform.tfstate"
        
        $sqlServer = terraform output -raw sql_server_name
        
        echo "SQL_SERVER=$sqlServer" >> $env:GITHUB_ENV
        
        Write-Host "SQL Server: $sqlServer"

    - name: Add the database
      shell: pwsh
      run: |
        Write-Host ('Environment: {0}' -f ${{ env.Environment }})
        Write-Host ('Database: {0}' -f ${{ env.Database }})
        Write-Host ('Recovery Model: {0}' -f ${{ env.RecoveryModel }})
        try {
          # Create credential
          $securePassword = ConvertTo-SecureString "${{ secrets.SQL_ADMIN_PASSWORD }}" -AsPlainText -Force
          $credential = New-Object System.Management.Automation.PSCredential ("sqladmin", $securePassword)
          
          # Connection parameters
          $db = @{
              SqlInstance   = "${{ env.SQL_SERVER }}.database.windows.net"
              SqlCredential = $credential
              Database      = ${{ env.Database }}
              EnableException = $true
          }
          New-DbaDatabase @db
        } catch {
          Throw $_
        }
            
    - name: Deploy database with SqlPackage
      uses: azure/sql-action@v2.3
      with:
        connection-string: 'Server=${{ env.SQL_SERVER }}.database.windows.net;Database=${{ env.Database }};User Id=sqladmin;Password=${{ secrets.SQL_ADMIN_PASSWORD }};Encrypt=true;'
        path: ${{ env.DATABASE_PROJECT }}
        action: 'publish'
        build-arguments: '-c Release'                 # Optional build options passed to dotnet build
        arguments: '/p:DropObjectsNotInSource=false /p:BlockOnPossibleDataLoss=true'
        sqlpackage-path: 'C:\Program Files\Microsoft SQL Server\170\DAC\bin\sqlpackage.exe'

    - name: Close Issue
      shell: pwsh
      run: |
        gh auth login --with-token $env:GITHUB_TOKEN
        gh issue close ${{ github.event.issue.number }} -R jpomfret/dbatools-githubactions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        

