name: Build and deploy database

# Set environment variables for all the jobs
env:
  database: Cats
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

defaults:
  run:
    working-directory: ./demos/database/

# Controls when the workflow will run
on:
  # Only allow workflow to run after merge has been accepted
  push:
    branches:
      - main
    paths:
        - demos/database/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v5
      
      - name: Where am i?
        run: pwd

      - uses: azure/sql-action@v2.3
        with:        
          connection-string: ${{ secrets.SQL_CONNECTION_STRING }}
          path: './demos/database/CatsOfTheWorld/CatsOfTheWorld.sqlproj'
          action: 'publish'
          build-arguments: '-c Release'                 # Optional build options passed to dotnet build
          arguments: '/p:DropObjectsNotInSource=true'   # Optional properties and parameters for SqlPackage Publish
          sqlpackage-path: 'C:\Program Files\Microsoft SQL Server\170\DAC\bin\''