name: Build and deploy database

defaults:
  run:
    working-directory: ./demos/database/

on:
  push:
    branches:
      - main
    paths:
        - demos/database/**

  workflow_dispatch:

jobs:
  
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v5
      
      - name: Where am i?
        run: pwd
      
      - name: What files do we have?
        run: ls

      - uses: azure/sql-action@v2.3
        with:        
          connection-string: ${{ secrets.SQL_CONNECTION_STRING }}
          path: './demos/database/CatsOfTheWorld/CatsOfTheWorld.sqlproj'
          action: 'publish'
          build-arguments: '-c Release'                 # Optional build options passed to dotnet build
          arguments: '/p:DropObjectsNotInSource=true'   # Optional properties and parameters for SqlPackage Publish
          sqlpackage-path: 'C:\Program Files\Microsoft SQL Server\170\DAC\bin\sqlpackage.exe'